In [1]:
import numpy as np

In [2]:
np.array ([10,20,30])

array([10, 20, 30])

In [3]:
m = np.array ([10,20,30])
print (m)

[10 20 30]


In [4]:
print (type (m))

<class 'numpy.ndarray'>


In [6]:
m = np.array ([])
print (m)

[]


In [7]:
m = np.array ([10,20,30])
print (m)

[10 20 30]


In [8]:
m.ndim

1

In [9]:
m.shape

(3,)

In [10]:
m = np.array ([[10,20,30], [40,41,42]])
print (m)

[[10 20 30]
 [40 41 42]]


In [11]:
m.ndim

2

In [12]:
m.shape

(2, 3)

In [13]:
m = np.array ([[10,'Sat',30], [40,41,42]])
print (m)

[['10' 'Sat' '30']
 ['40' '41' '42']]


In [14]:
m = [[10,'Sat',30], [40,41,42]]
print (m)

[[10, 'Sat', 30], [40, 41, 42]]


In [15]:
m = np.array ([[10,20,30], [40,42]])
print (m)

[list([10, 20, 30]) list([40, 42])]


C:\Users\noble\AppData\Local\Temp\ipykernel_9936\1061998992.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  m = np.array ([[10,20,30], [40,42]])


In [16]:
m = np.array ([[10,20,30], [40,0, 42]])
print (m)

[[10 20 30]
 [40  0 42]]


In [17]:
m = np.array ([[10,20,30], [40,np.NaN, 42]])
print (m)

[[10. 20. 30.]
 [40. nan 42.]]


In [18]:
import numpy as np
array1 = np.array ([10,12,14,16,20])
print (array1)


[10 12 14 16 20]


In [19]:
list1 = [[10,20,30],[50,60,70]]
print (list1)


[[10, 20, 30], [50, 60, 70]]


In [20]:
a= np.array (list1)
print (a)


[[10 20 30]
 [50 60 70]]


In [21]:
ar1 = np.array([[10,20,30,40],[50,60,70, np.nan]])
ar1


array([[10., 20., 30., 40.],
       [50., 60., 70., nan]])

In [23]:
list1 = [[10,20,30],[50,60,70,80]]
print (list1)

[[10, 20, 30], [50, 60, 70, 80]]


In [24]:

a= np.array ([[10,20,30],[50,60,70,80]])
print (a)
print (type(a))


[list([10, 20, 30]) list([50, 60, 70, 80])]
<class 'numpy.ndarray'>


C:\Users\noble\AppData\Local\Temp\ipykernel_9936\16576860.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a= np.array ([[10,20,30],[50,60,70,80]])


In [26]:

a= np.array ([[10,20,30],[50,60,80]])
print (a)
print (type(a))

[[10 20 30]
 [50 60 80]]
<class 'numpy.ndarray'>


In [27]:
list1 = [10,20,30,40,50,'X']
import numpy as np
array1 = np.array (list1)
print (type(array1))
print (type(list1))
print (list1)
print (array1)


<class 'numpy.ndarray'>
<class 'list'>
[10, 20, 30, 40, 50, 'X']
['10' '20' '30' '40' '50' 'X']


In [28]:
array1

array(['10', '20', '30', '40', '50', 'X'], dtype='<U11')

In [30]:
list1 = [10,20,30,40,50,60,70,80]
list2 = list1 [:3]
list2

[10, 20, 30]

In [33]:
list2[1] = 200
print (list2)

[10, 200, 30]


In [34]:
print (list1)

[10, 20, 30, 40, 50, 60, 70, 80]


In [35]:
arr1= np.array ([10,20,30,40,50,60,70,80])
arr2 = arr1[:3]
print (arr1)
print (arr2)

[10 20 30 40 50 60 70 80]
[10 20 30]


In [37]:
arr2[1]= 222
print (arr1)
print (arr2)

[ 10 222  30  40  50  60  70  80]
[ 10 222  30]


In [39]:
print (id (arr1))
print (id (arr2))

1925508414128
1925508412784


In [40]:
arr1= np.array ([10,20,30,40,50,60,70,80])
arr2 = arr1[:3].copy()
print (arr1)
print (arr2)

[10 20 30 40 50 60 70 80]
[10 20 30]


In [41]:
arr2[1]= 222
print (arr1)
print (arr2)

[10 20 30 40 50 60 70 80]
[ 10 222  30]


In [43]:
a = np.arange (5)
a

array([0, 1, 2, 3, 4])

In [44]:
a = np.arange (5,10)
a

array([5, 6, 7, 8, 9])

In [45]:
a = np.arange (5,10,2)
a

array([5, 7, 9])

In [46]:
a = np.arange (10,100,10)
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [47]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
a = a.reshape((3,3))
print (a)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [49]:
a = a.reshape((4,2))
print (a)


ValueError: cannot reshape array of size 9 into shape (4,2)

In [50]:
a = np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [52]:
print (a.reshape (10,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]


In [53]:
print (a.reshape (6,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [54]:
print (a.reshape (2,15))

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [55]:
print (a.reshape (2,5,3))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [56]:
m = a.reshape (2,5,3)
m

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [57]:
m.shape

(2, 5, 3)

In [58]:
m.ndim

3

In [60]:
 m.reshape (6,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [61]:

b = np.zeros((5,5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [62]:

b = np.zeros((4,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [63]:

b = np.ones((4,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [64]:
b*5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [65]:
mat1 = np.arange (0,30)
mat2 =np.reshape (mat1,(6,5),'F')
print (mat1)
print (mat2)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


In [66]:
mat2 =np.reshape (mat1,(6,5),'F')
print (mat2)

[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


In [67]:
mat2 =np.reshape (mat1,(6,5))
print (mat2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [69]:
mat2.T

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

In [70]:
a = np.arange (9)
a = a.reshape (3,3)
print (a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [71]:
b = np.arange (2,11)
b = b.reshape (3,3)
print (b)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [72]:
a+b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [73]:
b-a

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [74]:
b*a

array([[ 0,  3,  8],
       [15, 24, 35],
       [48, 63, 80]])

In [75]:
b/a

C:\Users\noble\AppData\Local\Temp\ipykernel_9936\2243761560.py:1: RuntimeWarning: divide by zero encountered in true_divide
  b/a


array([[       inf, 3.        , 2.        ],
       [1.66666667, 1.5       , 1.4       ],
       [1.33333333, 1.28571429, 1.25      ]])

In [76]:
b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [77]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [78]:
a %b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [79]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [80]:
b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [81]:
a*b

array([[ 0,  3,  8],
       [15, 24, 35],
       [48, 63, 80]])

In [82]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [83]:
b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [84]:
a@b

array([[ 21,  24,  27],
       [ 66,  78,  90],
       [111, 132, 153]])

In [87]:
mat2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [88]:
print (mat2.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [89]:
a = np.arange(30)
b = a.reshape(2,5,3)
print (b)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [90]:
print (b.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [91]:
vector = np.linspace(0,30,11)
print (vector)



[ 0.  3.  6.  9. 12. 15. 18. 21. 24. 27. 30.]


In [92]:
vector = np.linspace(0,20,5)
print (vector)

[ 0.  5. 10. 15. 20.]
